### ISSUE TITLE
White screen when sending on 2.0.4

### ISSUE THREAD

**Issue by IntNulls** [ETCDEVTeam/emerald-wallet#1009]
White screen when clicking send

**Comment by gagarin55** [comment]
Could you please check latest version from http://builds.etcdevteam.com/
and provide some details - your OS, ETH or ETC ?

**Comment by gagarin55** [comment]
Fixed in [2.1.0](https://github.com/ETCDEVTeam/emerald-wallet/releases/tag/v2.1.0)
