### ISSUE TITLE
rub error

### ISSUE THREAD

**Issue by MrMini1025** [ETCDEVTeam/emerald-wallet#1048]
When i switch currency to RUB, wallet can't connect to Emerald Service

[usd screenshot](https://i.ibb.co/Q7BkR4b/photo-2019-11-23-14-32-52.jpg)
[rub screenshot](https://i.ibb.co/k8kLmry/photo-2019-11-23-14-32-04.jpg)

**Comment by splix** [comment]
We currently do not provide conversion to RUB, but it's a bug that it's shown as a connection error.  Thank you for reporting the issue.

**Comment by splix** [comment]
Fixed on server, will be available on the wallet (i.e. fixed) in the following days

**Comment by splix** [comment]
Rolled to production servers, RUB should be working now
