### ISSUE TITLE
Build scripts

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#228]
Currently we have bunch of separate scripts/commands, will be more usable to organize it as grunt build script.

 - [ ] setup emerald-vault, (`dependencies.sh`)
 - [ ] run web/electron
 - [ ] prepare version (in `.travis.yaml`)
 - [ ] dist
 - [ ] deploy to GCP (`deploy.sh`)

**Comment by Cyberlane** [comment]
Is there any reason why you want this done with grunt specifically, and not just pure node? I do this on a couple clients projects and find it to be much cleaner, and removes the dependency of grunt.

**Comment by splix** [comment]
Basically we're already using _pure scripts_, such as `dependencies.sh`, but it's not really convenient. I'd like to see one modular build script, that would verify and apply all dev/build-related steps in an OS-independent way. It seems that Grunt or Gulp can provide it

**Comment by pocesar** [comment]
@Cyberlane it's a matter of not reinventing the wheel. there are so many plugins for grunt, that make up for the "extra" setup code (Gruntfile.js). Gulp IMHO is even better, although with a smaller community, but it's streaming interface make it really easy to use even non-Gulp plugins

**Comment by gagarin55** [comment]
Closing this, npm scripts is enough for now
