### ISSUE TITLE
Impossible to see total blocks during syncing on Windows

### ISSUE THREAD

**Issue by ghost** [ETCDEVTeam/emerald-wallet#286]
![image](https://user-images.githubusercontent.com/39793/28593338-4335889a-718c-11e7-9b7d-56297d4d019d.png)

**Comment by dulanov** [comment]
I don't see current progress status, how many percents and don't know about current final block number, not critic, but IMHO better expand.

**Comment by gagarin55** [comment]
We can use Tooltip component from new Material-UI lib after #325
