### ISSUE TITLE
Cant Delete Wallets

### ISSUE THREAD

**Issue by pooks** [ETCDEVTeam/emerald-wallet#302]
Cant delete a wallet after you make a new one

**Comment by elaineo** [comment]
@splix do we need to add `emerald_deleteAccount` or should this be `emerald_hideAccount` ?

**Comment by splix** [comment]
`emerald_deleteAccount` I think

**Comment by dulanov** [comment]
On UI side we should check account balance and add double protection for accounts with not zero balance for both chains.

**Comment by dulanov** [comment]
@pooks what do you think about this usecase:

If account hasn't balance, just show `delete` option, otherwise show only `hide` and in hidden menu additionally `delete` and if user click `delete`, show warning and then force export keystore file firstly.

**Comment by dulanov** [comment]
@splix if we allow users easily remove accounts with non-zero balances, it will catch up us, we should at least explicitly export account's keystore files before deletion that the user was able to make a backup and indirectly took the responsibility for their savings.
