### ISSUE TITLE
Release 0.6

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#326]
**Goal of the milestone**: full functionality for a wallet
**Release timeframe**: end of September

## New features

 - [x] send tokens
 - [x] mnemonic code for an address
 - [x] delete account #302 

## Refactoring

 - [x] use stateless redux, extends of classes `extends React.Component`
 - [x] refactor state zones - #234 
 - [x] check syntax with eslint #375

## Other

 - [x] produce build artifacts only when deploying
 - [x] use prebuilds Emerald Vault / CLI binaries, instead of compilation

**Comment by realcodywburns** [comment]
whats the status of `mnemonic code for an address`
