### ISSUE TITLE
Upgrade existing Geth on start

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#341]
Keep hashes of geth binaries in config (within download urls), and verify existing binary if it has correct hash. If not, app should download fresh geth and replace existing.

**Comment by whilei** [comment]
It would be nice if this "auto-update" feature had a user setting to disable auto-updating as well.

**Comment by splix** [comment]
@whilei agree. Ideally we should ask user if he wants to update
