### ISSUE TITLE
Repeat doesn't work

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#343]
On TX screen by clicking on Repeat button I expect that a Send Transaction form will be opened and filled with details from current transaction

**Comment by TomaszWaszczyk** [comment]
I can solve it.

**Comment by gagarin55** [comment]
@TomaszWaszczyk lets do it ;)

**Comment by BelfordZ** [comment]
takin a look at this.

So far I have the UI routing, but im running into bug. Will file an issue with more details soon
