### ISSUE TITLE
Please provide an AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [ETCDEVTeam/emerald-wallet#378]
As per

https://github.com/ethereumproject/emerald-wallet/blob/23e266681bd47f657a2750b98d42572ed85a52b4/package.json#L183

emerald-wallet is already configured to be bundled as an AppImage. It would be great if you could provide an AppImage for download on [GitHub Releases](https://github.com/ethereumproject/emerald-wallet/releases).

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Looks like the AppImage is getting built: https://travis-ci.org/gagarin55/emerald-wallet/jobs/329901675#L1675

**Comment by gagarin55** [comment]
Yes, it will be in the next release soon
