### ISSUE TITLE
Incorrect ETC total displayed on windows client

### ISSUE THREAD

**Issue by ajborn** [ETCDEVTeam/emerald-wallet#392]
# Overview

On Windows 10 the wallet displays the incorrect total amount of ETC. It actually shows a doubled amount.
This is not an issue on Ubuntu 16.04.

![doubleamountofetc](https://user-images.githubusercontent.com/5026351/33510699-14e45960-d6c4-11e7-9895-3272e8d331bd.png)

**Comment by gagarin55** [comment]
Do you have same total after wallet restarting ?

**Comment by ajborn** [comment]
@gagarin55 Negative the doubled total is still displayed.

Issue is specific to **epool.io**

**Comment by gagarin55** [comment]
`~` It means _approximately_ not negative

**Comment by gagarin55** [comment]
Could you please upgrade to RC3 version.
