### ISSUE TITLE
disable hide account feature for accounts not managed through emerald (ie geth accounts)

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-wallet#405]
![screen shot 2017-12-08 at 11 30 15](https://user-images.githubusercontent.com/10228550/33777645-466380e6-dc0b-11e7-83f3-12df838a7168.png)

For accounts not managed through the Emerald backend, the hide feature should be disabled (visible, but greyed-out) instead of just absent.

**Comment by gagarin55** [comment]
Actually, these accounts are from Ledger Nano, why we should disable hide/remove  functionality for such accounts ?

**Comment by splix** [comment]
Hide/remove is disabled for accounts with a balance to avoid losing PK for account with money. For ledger it's not an issue, as PK is stored in HW key anyway, just matter of displaying it with other accounts. I think it should be possible to remove Ledger backed accounts

**Comment by shanejonas** [comment]
I don't think we show geth accounts, just ones you've imported yourself
