### ISSUE TITLE
Not showing Ether amount 

### ISSUE THREAD

**Issue by athmane2197** [ETCDEVTeam/emerald-wallet#421]
It's showing Loading still 2 hours but when i see my account to http://gastracker.io/ it display to reel amount

**Comment by gagarin55** [comment]
Provide us with screenshots

**Comment by splix** [comment]
It happened to me many times, I believe that a public node provided by epool.io is too loaded. In logs I see that for many requests I get 503 code, so at some point emerald lose some important part of information and stuck in "loading" state forever

**Comment by gagarin55** [comment]
For Emerald Wallet it is preferable to use **local full node***. There is not reliable remote service for ETC like infura for ETH
