### ISSUE TITLE
Emerald wallet is not starting

### ISSUE THREAD

**Issue by denizaho93** [ETCDEVTeam/emerald-wallet#446]
The wallet can't start and it shows errors in the Console(Failed to start services error 504 gateway time-out//Failed prop type 
![img_0307](https://user-images.githubusercontent.com/34586647/35276763-1fa1248e-004d-11e8-8e56-14fc43f4eccf.JPG)
![img_0308](https://user-images.githubusercontent.com/34586647/35276764-1fc0c92e-004d-11e8-906b-3f423eab0f58.JPG)
![img_0309](https://user-images.githubusercontent.com/34586647/35276765-1fdafb5a-004d-11e8-9fc2-db8903e37a13.JPG)

**Comment by gagarin55** [comment]
@denizaho93 How its going ? Did you run wallet ?

**Comment by denizaho93** [comment]
No, I didn’t. It’s been like that all the time. I really don’t know what to do. Do you have any idea?

**Comment by denizaho93** [comment]
@gagarin55 No, I didn’t. It’s been like that all the time. I really don’t know what to do. Do you have any idea?

**Comment by splix** [comment]
@denizaho93 does it work with version 0.8?

**Comment by denizaho93** [comment]
@splix Do you mean version 0.8 of Emerald Wallet? I haven't tried yet.
