### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by tzdybal** [ETCDEVTeam/emerald-wallet#459]
I cant see some of my transactions. I'm using geth, I'm fully synced, the total amount is correct, but I'm not able to see the transactions - I have only 2 incoming transactions (after filtering).

I'm using latest Linux build from builds.etcdevteam.com.

**Comment by pyskell** [comment]
This issue is present in 0.10 RC4

**Comment by shanejonas** [comment]
This is because there was no way to get history without walking the entire blockchain. There is now an index for `address -> txes` that will be used to get this data: https://github.com/ethereumproject/go-ethereum/pull/475

**Comment by shanejonas** [comment]
related to #473

**Comment by BelfordZ** [comment]
duplicates #473
