### ISSUE TITLE
Geth Not Starting... Stuck at "Launching Geth Backend"

### ISSUE THREAD

**Issue by lawrenceong001** [ETCDEVTeam/emerald-wallet#469]
After I Installed Emerald Wallet - v0.8.0 RC 2, I'm not able to start the wallet. 

this is what I get: 
![image](https://user-images.githubusercontent.com/8312221/35716455-12ee2262-07a7-11e8-8884-b14eb8f15ce6.png)

please note that this computer had 0.8.1 and 0.9.1 of the Ethereum Classic Wallet running before, and I hadn't touched it in a while but would like to restart it again. 

am I missing any prerequisites? 

thanks.

**Comment by gagarin55** [comment]
There should be logs of geth.exe located in %USERPROFILE%\AppData\Roaming\EmeraldWallet\logs

Could you please check it

**Comment by lawrenceong001** [comment]
Hi,

the log folder shows nothing. 
![image](https://user-images.githubusercontent.com/8312221/35740041-92a8b5c6-0801-11e8-83da-2ac431ebae77.png)

are there requirements i'm missing?
