### ISSUE TITLE
Emerald Wallet 0.7 RC1 is unable to list all transactions

### ISSUE THREAD

**Issue by pcdinh** [ETCDEVTeam/emerald-wallet#473]
Windows 10
Emerald 0.7.0 RC 1

In my wallet only the first transaction is displayed. Sub-sequential incoming transactions don't, even when ALL filter is selected

Screenshot: https://ibb.co/b9pYTx

**Comment by pcdinh** [comment]
Upgraded to v0.8 RC2. Same issue

**Comment by splix** [comment]
Currently there are no standard RCP API to get list of transactions for an address. Emerald can only show transactions made from current instance of Emerald Wallet, it keeps them in local storage for history but it doesn't know about any previous transactions or transactions made from another app.

This feature will be implemented soon
