### ISSUE TITLE
JSON RPC / HTTP as internal communication protocol is very expensive and unsecure

### ISSUE THREAD

**Issue by ghost** [ETCDEVTeam/emerald-wallet#48]
We can try three another approarches:
1. Linking statically as [Node.js Addon](https://nodejs.org/api/addons.html#addons_linking_to_node_js_own_dependencies)
2. Load dynamically via [ffi](https://www.npmjs.com/package/ffi)
3. Write native module via [Rust abstraction layer](https://github.com/neon-bindings/neon)

**Comment by dulanov** [comment]
Also [Using Native Node Modules](https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md).

**Comment by sjmackenzie** [comment]
@dulanov I might be able to take this on (after my FFI experience with sputnikvm).

**Comment by dulanov** [comment]
@sjm which variant do you prefer, dynamically linking via ffi, right?

**Comment by sjmackenzie** [comment]
@dulanov I cannot say atm but right now, as I'm disliking dynamically linked ffi intensely (I'll suffer through sputnikvm's ffi then smile), though it's probably the best way forward as I can just write ffi code once and it works for different languages. If the alternatives are easier... we need to consider if the easier choice limits other host languages - which defeats our objective. I cannot say just yet.

**Comment by dulanov** [comment]
For node.js there is a static linking option, but ffi i think the fastest and easiest way.

**Comment by sjmackenzie** [comment]
maybe, we need to choose data types that are suitable for the lowest common denominator language. Say for example C. What I'm looking at is this:

I want to define the interface for sputnikvm in terms of a capnp schema. This allows us to 1) easily evolve it 2) have very clear documentation about input output specs 3) formatted in wire, disk friendly format.
The second thing is I want to reduce the schema down to an array of `u8` which is a Vec<capnp::Word>. The trick is being able to reconstitute the original data. So both the sender and receiver convert their data into arrays of `uint8_t`. For my use case I think this can be constructed and reconstituted by any language with a sufficiently expressive enough capnp compiler plugin. 

I would imagine emerald-rs would have similar requirements. There are a few snags, like does the host language have a suitably implemented capnproto compiler plugin. This is a limiting factor. 

Deciding not to base the interface on a capnp schema means we need to define it using functions and data types. In this case it would be easier and more languages would be able to access it. .. writing this comment makes me think I should use the same way and not pass an array of `uint8_t`. 

Let me try option 2 on sputnikvm now.

**Comment by elaineo** [comment]
@sjmackenzie so, what'll it be? Load dynamically via ffi? :)

**Comment by dulanov** [comment]
@elaineo yes, for public beta we want to embedd emerald-rs as dynamic library via ffi.

**Comment by gagarin55** [comment]
Finally we ended up with native module implemented in Rust
