### ISSUE TITLE
Confirm password field

### ISSUE THREAD

**Issue by tzdybal** [ETCDEVTeam/emerald-wallet#483]
When I import private key, I need to insert strong password. It would be cool to have "confirm password" field, so I won't block myself by accident (typo, CAPS LOCK, etc).

For "Generate", there is at least "Show password" button in the input field, but I would also like to retype password for confirmation.

**Comment by whilei** [comment]
Perhaps out of the scope of this issue and even the project, but just as a point of interest from the "strong" password idea -- https://github.com/cupslab/password_meter
