### ISSUE TITLE
Display warning when network is not fully synchronized

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#489]
When blockchain is not yet fully synchronised show an alert box in header telling a user that displayed balances are not correct. 

Red if it's more than 100000 blocks to synchronize, Yellow if's more than 10000, and Blue or Light Yellow when it's more than 400. (let's discuss numbers/colors)

**Comment by TomaszWaszczyk** [comment]
I just synchronize blockchain and did not know whethere it is a proper behaviour or not and why balances are not correct. Now I know. Thanks!

**Comment by splix** [comment]
Yeah, most people not realize that you have to wait for a full sync to see final correct balance. Unfortunately it take a long time to sync, more than a week for a full sync on an average machine.

**Comment by splix** [comment]
rel #488

**Comment by shanejonas** [comment]
fixed in #503
