### ISSUE TITLE
ERROR 521

### ISSUE THREAD

**Issue by chengtuo** [ETCDEVTeam/emerald-wallet#492]
Hello, I used the EmeraldWallet0.7.0RC wallets on January 8, 2018 and I transferred 1368.069 ETC coins between January 8, 2018 and January 31, 2018, however, while using Emerald , Can not be transferred out, turn out the prompt error, wallet only shows the total number of coins, I check the relevant block browser, but do not understand, I am an ordinary investor, I am very anxious, I like the coin ETC , Put it in the wallet to keep. My next step how to do, my money is still not in the end, please reply, thank you very much.

**Comment by chengtuo** [comment]
I keep json file, I like etc coins, like this team, I will put in this wallet, until this wallet is successful, although I can only see the total number of coins, can not be transferred out, but I believe you, I believe you Can succeed. I am waiting for your good news.

**Comment by splix** [comment]
Do you use local geth or a remote node?

**Comment by chengtuo** [comment]
a remote node，for windows

**Comment by splix** [comment]
Can you show us which error do you get?

**Comment by chengtuo** [comment]
Yesterday, I tried to send out, showing the error, shown below "", upgrade to the latest version today, nor, showing 521, there is no prompt。
![etcerror](https://user-images.githubusercontent.com/31432807/36521252-d8f8c4f6-17d0-11e8-8e20-4ee5d8f44309.png)

**Comment by chengtuo** [comment]
The above is a 7.0.1 prompt error

**Comment by splix** [comment]
are you sure you enter a correct address which starts with `0x`?

**Comment by splix** [comment]
and which remote node do you use? can you try another one? gastracker instead of epool, or opposite

**Comment by chengtuo** [comment]
![etcrec](https://user-images.githubusercontent.com/31432807/36521589-6d4426b8-17d2-11e8-8ad1-06789533e545.png)

**Comment by chengtuo** [comment]
Do you need my wallet address, I will actively cooperate with you to solve the problem. I am anxious.

**Comment by splix** [comment]
Try with another remote first. If you get error 521 it's a connection error, and maybe just temporal

**Comment by chengtuo** [comment]
I have three computers, all using the remote 7.0.1, because there is no synchronization, save time, but each computer is independent, with a local area network

**Comment by splix** [comment]
521 is a connection error on another side. See https://support.cloudflare.com/hc/en-us/articles/200171916-Error-521-Web-server-is-down

**Comment by chengtuo** [comment]
![exp](https://user-images.githubusercontent.com/31432807/36521835-02c12f3c-17d4-11e8-9059-37bc0a7e8a65.png)

**Comment by chengtuo** [comment]
My currency is still not, this did not turn successful, scared me, my next step how to do?

**Comment by splix** [comment]
do you get same error when you switched to different remote? or different error?

**Comment by chengtuo** [comment]
![etc1](https://user-images.githubusercontent.com/31432807/36522232-56d4e4ae-17d6-11e8-996b-e59e2e1a1945.png)

**Comment by splix** [comment]
can you elaborate please? do you mean it cannot connect to gastracker? how long did you wait?

**Comment by chengtuo** [comment]
Updated to the latest version this morning, the original record of several transactions are not on the screen.

**Comment by chengtuo** [comment]
I am in mainland China, because I do not know English, I need to use Google translation, but the mainland can not access Google sites, so with VPN, VPN software is affected?，WAIT FOR 5 MINS

**Comment by splix** [comment]
That maybe a reason, it could be a problem to use remote nodes from China.
At this case more safe would be using a local node. It takes several days to synchronize the network at this case though.

**Comment by chengtuo** [comment]
![etc2](https://user-images.githubusercontent.com/31432807/36522559-39703858-17d8-11e8-83ef-16b138700e35.png)

**Comment by chengtuo** [comment]
The figure above always read the data, I switched to EPOOL, as shown below
![etc3](https://user-images.githubusercontent.com/31432807/36522637-b074437c-17d8-11e8-9712-41b43a3b0faa.png)

**Comment by chengtuo** [comment]
![etc4](https://user-images.githubusercontent.com/31432807/36522679-eb8db2cc-17d8-11e8-8366-161e3b9b5421.png)

**Comment by chengtuo** [comment]
Now I switch node, please wait.

**Comment by splix** [comment]
I see, gastracker stuck in "loading", probably slow to access from China. Unfortunately we cannot do anything with that, and I suggest to use a full local node at this case. Or be very patient

**Comment by chengtuo** [comment]
Then I now need to reinstall or how to operate local nodes, I need how to operate, thank you!

**Comment by chengtuo** [comment]
Thank you very much for your patience and your time. I'm going to make a wallet with all nodes. Do I keep the JSON file and import it to see all my coins?

**Comment by chengtuo** [comment]
I open the wallet for a period of time, can operate normally, thank you very much!

**Comment by zunnamu** [comment]
i have problem about error#521 to
![521](https://user-images.githubusercontent.com/35390125/36603347-ca920f16-18fd-11e8-82e8-579da92646c8.jpg)
