### ISSUE TITLE
Button for send transaction can be clicked more than once in a rapid succession

### ISSUE THREAD

**Issue by BelfordZ** [ETCDEVTeam/emerald-wallet#501]
The button "SEND x.xxx ETC" should be disabled after the first click, and subsequent clicks should not double send
![doublesend](https://user-images.githubusercontent.com/1787231/36714929-e471b4f2-1b48-11e8-8a88-481981a87d0c.gif)

**Comment by BelfordZ** [comment]
could use `_.once(onClickHandler)`, or `_.throttle`, `_.debounce`. All solid options

**Comment by gagarin55** [comment]
Thanks for report, we are considering to refactor sending process.

**Comment by BelfordZ** [comment]
After moving the password to a seperate page, it seems that this is no longer possible.

fixed!
