### ISSUE TITLE
EMERALD WALLET Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.

### ISSUE THREAD

**Issue by Dmytro459** [ETCDEVTeam/emerald-wallet#506]
Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.
please help me. wallet does not send money

**Comment by Dmytro459** [comment]
the problem was solved by updating the version of the wallet, removed 7 installed 8. If you put top 8 7 purse hangs on startup

**Comment by hinhrt** [comment]
Thanks! Worked for me. I did what @Dmytro459 said (put the wallet application in a separate directory) and it worked.
