### ISSUE TITLE
ETC Emerald Wallet syncing very slow.

### ISSUE THREAD

**Issue by INVICT-xx** [ETCDEVTeam/emerald-wallet#512]
Its been 2 days and my ETC Emerald Wallet is still not updated.  I transferred some ETC from Bittrex which is still not showing in the wallet but shows transfer complete in Bittrex. Please help with some step as to how I can I speed up the Sync Process and show my ETC?

**Comment by splix** [comment]
If you use a local node please wait until full chain is synchronized. Current block height is 5497117, and it usually take more than a week to synchronize to that point on a modern hardware

**Comment by INVICT-xx** [comment]
![etc](https://user-images.githubusercontent.com/813542/36956033-9129f540-1ff1-11e8-9880-efc208d6a072.jpg)

**Comment by INVICT-xx** [comment]
That's where it is now. Will my transfer be part of Hard Fork and the airdrop?

**Comment by splix** [comment]
You're good. On which block do you have that transaction? Also make sure it's not marked as FAILED.

**Comment by INVICT-xx** [comment]
Block Height
5489249
Block Hash
0x9f6e18be2ecf97cf4f48ff02ae49ab914316e21a8d3708f658e79359a657dc16

**Comment by splix** [comment]
so you have exactly same address as displayed on gastracker, you see balance on gastracker but nothing in emerald?

**Comment by INVICT-xx** [comment]
![etc1](https://user-images.githubusercontent.com/813542/36956519-68e4cd00-1ff4-11e8-881f-e8f33d5f037f.jpg)

**Comment by INVICT-xx** [comment]
Yes balance on Gas....Zero in wallet

**Comment by splix** [comment]
That's interesting. First of all, as Gastracker displays it, you got your transfer. It's strange you don't see in the wallet. Did you try to restart it?

**Comment by INVICT-xx** [comment]
Yep did several times.

**Comment by INVICT-xx** [comment]
@splix : Any help with this loss txn will be of great help

**Comment by INVICT-xx** [comment]
Woohoo!! I see my coin now!!

**Comment by splix** [comment]
We didn't do anything yet, it was a strange glitch. We'll take a look at it though. 
If it will happen next time, as I workaround I'd suggest to switch to a remote node (epool or gastracker, top right corner)

**Comment by INVICT-xx** [comment]
Thanks @Splix will try the workaround in case I face the same issue. Appreciate your help. You guys are doing a wonderful job.
