### ISSUE TITLE
password issues

### ISSUE THREAD

**Issue by warrentc3** [ETCDEVTeam/emerald-wallet#516]
I am unable to generate a paper wallet or transfer funds or view my private key.  The password I have saved is not working.  I even created two new wallets using the same password with copy/paste... one worked and one did not.  

Now I have lost funds... :(

Windows 10  using version: 0.8.1 RC 2

**Comment by warrentc3** [comment]
No sort of password validation field... the "eye" button doesn't even work to reveal the password typed.  
I regret using this software.

**Comment by BelfordZ** [comment]
If you can give exact steps for us to reproduce the issue you are having, I'd be happy to help.

Sorry to hear about the lost funds.

**Comment by warrentc3** [comment]
I've had very mixed results with using the software in general and Windows UAC.

**Comment by splix** [comment]
It's really hard to fix "mixed results". The development is still in progress, and we know there're many issues, but we can fix only things that were reported with some demonstration

**Comment by BelfordZ** [comment]
Any other ideas for how we can prevent this in the future?
