### ISSUE TITLE
Emerald Wallet Version: 0.8.1 RC 2 cannot load

### ISSUE THREAD

**Issue by Megareds** [ETCDEVTeam/emerald-wallet#525]
Hello! Emerald Wallet Version: 0.8.1 RC 2 cant load, it shows "starting..." with spining circle of dots, i was waiting for more then 8 hours, but without any result
Please help

**Comment by KryptoKangaroo** [comment]
Hi all,
I'm having the exact same problem, wallet was loading fine yesterday, today it just sits on startup screen?

**Comment by jRazer** [comment]
Same problem too,
[error] Failed to start Services: Error: 520: Origin Error
    at /opt/EmeraldWallet/resources/app.asar/node_modules/emerald-js/lib/rpc/transport.js:68:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Megareds** [comment]
index.js:82407 [10:16:32.472] Failed to start Services: Error: 520: Origin Error
    at C:\Users\1\AppData\Local\Programs\EmeraldWallet\resources\app.asar\node_modules\emerald-js\lib\rpc\transport.js:68:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)


Yes, i have the same

**Comment by shanejonas** [comment]
there are some issues with the default remote node, `epool`. you can follow this to reset them and try syncing the full node: https://github.com/ETCDEVTeam/emerald-wallet#troubleshooting

I have fixed it getting stuck here #523, its not shipped yet though so the above solution should work until then

**Comment by pyskell** [comment]
For the troubleshooting section you may want to clarify which of the files (if any) contain key storage and therefore should **NOT** be deleted.

I realize this is the wrong section but wanted to mention it to prevent any newbies from troubleshooting themselves out of ETC. Feel free to correct me if keys aren't stored in these directories at all :smile:

**Comment by shanejonas** [comment]
@pyskell clearing that directory is _only_ application related settings. you will _NOT_ lose keys deleting that. But yes, please use common sense and caution when just deleting files 😄 and back up your keys!

**Comment by pyskell** [comment]
Haha, good to know, I've actually carefully backed up and then deleted that folder previously.

**Comment by Pepperok85** [comment]
Hi all. I have the same problem, how to solve it?

**Comment by shanejonas** [comment]
@Pepperok85 i've posted a workaround here: https://github.com/ETCDEVTeam/emerald-wallet/issues/525#issuecomment-372730674

**Comment by pyskell** [comment]
Just to clarify for others, since I managed to gloss over it.

The workaround is:

1. Delete your data folder as described here: https://github.com/ETCDEVTeam/emerald-wallet#troubleshooting
2. Select a full node when you restart Emerald Wallet and give it time to sync.

Remote nodes are causing the issue at the moment.

**Comment by IOTASTUCKINDEPOSIT** [comment]
After deleting data folder and selecting full node on restart, am I letting it sync on Mainnet or should I select Mainnet (epool.io).  I have selected Mainnet and it seems to be taking a while

**Comment by splix** [comment]
@IOTASTUCKINDEPOSIT epool.io is currently under heavy load, that's there reason why people has this problem. You **should not** choose epool at this moment. You need to choose _Mainnet_, that's going to be a local node, takes a week to sync, or _Mainnet (gastracker.io)_, which is a remote node.

**Comment by IOTASTUCKINDEPOSIT** [comment]
Got it.  Thanks Splix !
