### ISSUE TITLE
Emerald WIN10 Desktop Wallet Not Starting

### ISSUE THREAD

**Issue by IOTASTUCKINDEPOSIT** [ETCDEVTeam/emerald-wallet#528]
So, I have an Ethereum Classic Emerald Wallet on my WIN10 desktop. It was working fine until I closed it and tried to reopen it. It hangs on "starting" and never fully starts/opens/launches. Any help on this would be greatly appreciated.

**Comment by shanejonas** [comment]
Hi, Remote nodes are causing the issue at the moment. There is a fix in an upcoming release. For now:

- Delete your data folder as described here: https://github.com/ETCDEVTeam/emerald-wallet#troubleshooting
- Select a full node when you restart Emerald Wallet and give it time to sync.

this workaround is from: https://github.com/ETCDEVTeam/emerald-wallet/issues/525#issuecomment-373057764
