### ISSUE TITLE
Unnecessary plus sign

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#536]
In initial design there were idea about marking accounts with fresh incoming transactions with a plus sign:
![plus](https://user-images.githubusercontent.com/48364/37680798-5c10a0d6-2c5b-11e8-873d-7278e58c6365.png)

We currently don't have this feature, but all accounts are marked with "plus" instead. Let's remove it. Maybe later we'll implement this feature, and will return that marker for active accounts

**Comment by shanejonas** [comment]
the `+` currently expands all of your tokens. should we remove that, only show it on the `show` details page?

**Comment by splix** [comment]
That's unexpected
