### ISSUE TITLE
error occurs while send tokens. non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by caochao** [ETCDEVTeam/emerald-wallet#557]
i got a error dialog with prompt "non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R" while send tokens.
it happens occasionally.
related issues:
signTransaction should return r, s, and v without leading 0's
https://github.com/ETCDEVTeam/emerald-js/issues/38

**Comment by splix** [comment]
dup #863
