### ISSUE TITLE
ui: 'Accounts' and 'Accounts And Tokens' labels need padding on smaller resize

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-wallet#573]
at normal window size the `Accounts` and `Accounts And Token` headers look fine because they right-align exactly with container div below.
![screen shot 2018-05-08 at 00 30 34](https://user-images.githubusercontent.com/10228550/39710221-24d50612-5257-11e8-827b-a5783fe6fd4f.png)

... but then when the app window gets smaller they look kind of like a cowboy hat at a maroon 5 concert.

![act](https://user-images.githubusercontent.com/10228550/39710133-e2cafe98-5256-11e8-9f34-092dfa17a2d3.gif)

![screen shot 2018-05-08 at 00 30 46](https://user-images.githubusercontent.com/10228550/39710217-2256f77e-5257-11e8-87ee-17db72212b47.png)

**Comment by shanejonas** [comment]
I think we're just going to lock height/width for now, looking good at every resolution right now is a pretty big rabbit hole

**Comment by gagarin55** [comment]
New TopBar is coming in next release

**Comment by BelfordZ** [comment]
locked height and width  -- should be fixed
