### ISSUE TITLE
Wallet stuck in 'open wallet' step (Run in Development)

### ISSUE THREAD

**Issue by RonaldEAM** [ETCDEVTeam/emerald-wallet#579]
I followed all steps, ran `npm run setup` and `./dependencies.sh`, emerald and geth are in my project folder. Then I run `npm run build:all` and `npm run start:electron` but wallet hangs in third step with these errors:
![modt](https://user-images.githubusercontent.com/7190696/39947057-8b87aa92-553e-11e8-80ef-02a475d91be3.png)
![okds](https://user-images.githubusercontent.com/7190696/39947063-91103164-553e-11e8-8dc0-8cc5401cef31.png)
I'm using mainnet full node and I've already deleted `~/.config/EmeraldWallet`
These are fresh logs:
[log.log](https://github.com/ETCDEVTeam/emerald-wallet/files/1996890/log.log)

However when I run release version it works ok
I use Ubuntu 16.04

Not sure what i'm doing wrong, please your help would be much appreciated

**Comment by shanejonas** [comment]
I think `emerald` may not have shut down correctly, can you make sure its not running already in the background somewhere?

**Comment by RonaldEAM** [comment]
It was `emerald`, I think it wasn't builded properly first time with `dependencies.sh`, I tried downloading directly emerald 0.22.0 release and it worked, then I built emerald 0.20.0 again from source.

**Comment by BelfordZ** [comment]
Thanks @RonaldEAM
