### ISSUE TITLE
loose transfert

### ISSUE THREAD

**Issue by thlansac** [ETCDEVTeam/emerald-wallet#583]
hi i made a transfert etc to kraken i never receive my tokens and i can't find an history for my transaction.
It was during the fork. I wasn't abble to open emerald wallet and i reinstall it 
Regards,

**Comment by BelfordZ** [comment]
Is the wallet still syncing?

**Comment by thlansac** [comment]
nop i remove the program fully and réinstall it now the wallet working fine
but i can't find anywhere my tokens :\

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-05-16 17:36 GMT+02:00 Zachary Belford <notifications@github.com>:

**Comment by BelfordZ** [comment]
Sorry but you will need to give more information to help determine where the issue is.
