### ISSUE TITLE
Condensed layout issues

### ISSUE THREAD

**Issue by BelfordZ** [ETCDEVTeam/emerald-wallet#597]
![image](https://user-images.githubusercontent.com/1787231/40447977-11899f8a-5e89-11e8-9ac7-c9d3ddcb64e1.png)
1. balance overlaps address / copy button
2. 'add accounts / tokens' is aligned oddly
3. tx history has the tx value clipped out

**Comment by gagarin55** [comment]
1. Should be fixed after switching to Material UI v1, with new components for flex layout
2. Should be fixed in new Top bar implementation
3. Should be fixed in new Tx history design
