### ISSUE TITLE
no feedback about unconnected RPC

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-wallet#614]
I would expect to see a little red dot or some kind of warning that the application isn't connected to a any client endpoint.

![screen shot 2018-06-01 at 14 30 26](https://user-images.githubusercontent.com/10228550/40840801-707b9ac2-65a8-11e8-8a98-7efaa03e14ac.png)

**Comment by BelfordZ** [comment]
this one isnt super straight forward. @shanejonas and I tried a couple things, each having its own issue. We are wondering if this can wait for post v1. Thoughts @whilei ?

**Comment by whilei** [comment]
It seems kind of important to me... without a connected endpoint the wallet is missing a big part of it's _raison d'etre_ and the user should know about that. Are the issues essentially differentiating no-response vs invalid responses, or what?

**Comment by BelfordZ** [comment]
To break this issue down further (please help fill in blanks):

1. (already works) When starting the wallet, if geth is unavailable it will start geth itself, downloading it if necessary.

2. When starting the wallet, if any geth of the required rpc commands / features are not available in the currently running geth, notify the user of the missing features, and prompt them to....

3. When previously connected to a fully functioning geth, if geth becomes unreachable (timeout or status code ....??) we should....

4. anything else??


As another option, I would like to discuss re-working the network selector such that there are the following options:
1. Main net (will *always* download/boot correct version of geth for you, finding a port that is not in use and using a seperate data folder to avoid colliding with any currently running geth)
2. Custom RPC node (input an address to a node aka localhost:8545)
3. all the rest of the options stay the same

**Comment by BelfordZ** [comment]
By taking the alternative approach, we can make the problem "prompt the user when their node is unreachable" + "prompt the user when a particular RPC command is unavailable, and report on the effects of such command being unnavail"

**Comment by shanejonas** [comment]
👍 for custom RPC feature

Heres the existing ticket for that for reference: https://github.com/ETCDEVTeam/emerald-wallet/issues/314

**Comment by BelfordZ** [comment]
after talking with Isaac, We are gonna show a notification *on any error* when using geth rpc commands

**Comment by BelfordZ** [comment]
upcoming release will have an error dialog and a submit issue to github button
