### ISSUE TITLE
Image padding 

### ISSUE THREAD

**Issue by darcyreno** [ETCDEVTeam/emerald-wallet#615]
2 minor padding issues highlighted in yellow:

<img width="1309" alt="screen shot 2018-05-30 at 4 23 04 pm" src="https://user-images.githubusercontent.com/16766183/40844314-6e30f090-6568-11e8-8b8b-defe199a263a.png">

Also the checkbox in this page get's clipped oddly:

<img width="1197" alt="screen shot 2018-06-01 at 7 06 18 am" src="https://user-images.githubusercontent.com/16766183/40845133-9dc9ab38-656a-11e8-8080-e7a74cbb6312.png">

**Comment by darcyreno** [comment]
The refresh icon get's clipped on the left when refreshing
The confirmations success text needs some padding to stop clipping the right edge

**Comment by gagarin55** [comment]
Second screen is ok, because this is our "checked" icon ;) - https://github.com/ETCDEVTeam/emerald-svg-icons/blob/master/icons/check1.svg

**Comment by BelfordZ** [comment]
resolved now.
