### ISSUE TITLE
add new npm run clean command

### ISSUE THREAD

**Issue by BelfordZ** [ETCDEVTeam/emerald-wallet#618]
the command should:

 1. `rimraf node_modules`
 2. `npm cache clean --force`

please make suggestions / edits

**Comment by shanejonas** [comment]
`npm cache clean --force`

**Comment by gagarin55** [comment]
Its better to use `rimraf` insted of `rm`

**Comment by gagarin55** [comment]
```yarn clean:node_modules``` does the job
