### ISSUE TITLE
private chain trans in queue

### ISSUE THREAD

**Issue by ghost** [ETCDEVTeam/emerald-wallet#622]
1. start private chain
master@master:~/eth$ ./geth --dev --rpc --rpc-addr=127.0.0.1 --rpc-port 8545 --log-dir logs console 2>> node-01.log
Welcome to the Geth JavaScript console!

instance: Geth/v4.2.0-c999068/linux/go1.9.2
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> 

2. import two accounts

master@master:~/eth$ ./geth --dev account import key1
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Address: {2b4951cc54661664a04ec17b6060a7b010f266e3}
master@master:~/eth$ ./geth --dev account import key2
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Address: {1fe7dd83b86afb634ffc17d0d797ad17b131a78e}
master@master:~/eth$ 

3. call miner.start() in eth console
> miner.start();
true

3. open wallet, import two accounts

4. send 5etc to other account from one account.

5. now, eth state:
> eth
{
  accounts: ["0x2b4951cc54661664a04ec17b6060a7b010f266e3", "0x1fe7dd83b86afb634ffc17d0d797ad17b131a78e"],
  blockNumber: 34,
  coinbase: "0x2b4951cc54661664a04ec17b6060a7b010f266e3",
  compile: {
    lll: function(),
    serpent: function(),
    solidity: function()
  },
  defaultAccount: undefined,
  defaultBlock: "latest",
  gasPrice: 20000000000,
  hashrate: 501095,
  mining: true,
  pendingTransactions: [{
      blockHash: null,
      blockNumber: null,
      chainId: 62,
      from: "0x2b4951cc54661664a04ec17b6060a7b010f266e3",
      gas: 21000,
      gasPrice: 21782200000,
      hash: "0x1af207f82c82209173fcec11ed5b194bc8ef965e431891a224ced4be95d66c5e",
      input: "0x",
      nonce: 1048576,
      replayProtected: true,
      to: "0x1fe7dd83b86afb634ffc17d0d797ad17b131a78e",
      transactionIndex: null,
      value: 5000000000000000000
  }],
  syncing: false,
  call: function(),
  chainId: function(),
  contract: function(abi),
  estimateGas: function(),
  filter: function(fil, callback),
  getAccounts: function(callback),
  getBalance: function(),
  getBlock: function(),
  getBlockNumber: function(callback),
  getBlockTransactionCount: function(),
  getBlockUncleCount: function(),
  getCode: function(),
  getCoinbase: function(callback),
  getCompilers: function(),
  getGasPrice: function(callback),
  getHashrate: function(callback),
  getMining: function(callback),
  getNatSpec: function(),
  getPendingTransactions: function(callback),
  getStorageAt: function(),
  getSyncing: function(callback),
  getTransaction: function(),
  getTransactionCount: function(),
  getTransactionFromBlock: function(),
  getTransactionReceipt: function(),
  getUncle: function(),
  getWork: function(),
  iban: function(iban),
  icapNamereg: function(),
  isSyncing: function(callback),
  namereg: function(),
  resend: function(),
  sendIBANTransaction: function(),
  sendRawTransaction: function(),
  sendTransaction: function(),
  sign: function(),
  signTransaction: function(),
  submitTransaction: function(),
  submitWork: function()
}
> 

6. wallet transfer in queue.

where is the problem?

**Comment by shanejonas** [comment]
can you try using latest geth? 5.4 is latest

**Comment by yourihua** [comment]
@shanejonas yes, i try three version, wallet: master and 0.10.0 and 0.9.0,  and geth version: 5.4, 5.2 and 4.2.

**Comment by BelfordZ** [comment]
do you know the tx hash? could you run the geth commands to query the status of your tx? perhaps using `eth_getTransactionReceipt` to confirm that its pending / not pending from within your private network, or if this is an issue with the wallet.

**Comment by BelfordZ** [comment]
hmm okay. @yourihua I will fire up a private net and give this a try. Any additional details on how I can reliably reproduce the issue would be helpful :)

**Comment by yourihua** [comment]
@BelfordZ 
![image](https://user-images.githubusercontent.com/1717368/41757653-eb03a7ee-7615-11e8-8bd4-de217b2f1c0b.png)

![image](https://user-images.githubusercontent.com/1717368/41757664-f9cedb72-7615-11e8-815d-70a0560458e6.png)

**Comment by yourihua** [comment]
@BelfordZ first is send trans in console,and second in my wallet.

**Comment by BelfordZ** [comment]
Can you please try this again on master? We have fixed an issue with gas prices, though I'm not sure this will fix your issue.

**Comment by BelfordZ** [comment]
Just verified that transactions stay pending when running your own geth in `--dev` mode. Im gonna see if I can get it working, in the meantime I would recommend using something like sputnik-vm-dev or something like ganache.

**Comment by yourihua** [comment]
@BelfordZ i try ganache, but get error.

index.js:24017 Uncaught (in promise) Error: Unknown JSON RPC response: {"id":67,"jsonrpc":"2.0","result":0},
                     method: net_peerCount,
                     params: []
    at index.js:24017
    at <anonymous>

![image](https://user-images.githubusercontent.com/1717368/41804975-cf470fd8-76d2-11e8-9816-640297e5168c.png)

**Comment by yourihua** [comment]
@BelfordZ i try sputnik-vm-dev, now it work. thank you very much.

**Comment by BelfordZ** [comment]
I should note that when using ganache you may see errors, and some functionality not working properly. This is because classic geth has some features that are missing in ethereum mutable and vice versa.

**Comment by yourihua** [comment]
@BelfordZ How are you testing local?

**Comment by BelfordZ** [comment]
Most of the time I just test on main net with test tokens, or small amounts of ETC, or using sputnik-vm-dev. We are discussing with some of the geth guys how to get --dev working proper :)

**Comment by yourihua** [comment]
@BelfordZ good job.

**Comment by softgg** [comment]
@BelfordZ i use sputnik-vm-dev,then deploy a simple contract use remix Web3 Provider,but get "creation of A pending",and the contract is not deployed successful
![image](https://user-images.githubusercontent.com/14340821/42009260-26c88696-7abc-11e8-899f-577f567d816a.png)
