### ISSUE TITLE
Send transaction

### ISSUE THREAD

**Issue by akifromchina** [ETCDEVTeam/emerald-wallet#643]
Steps:
* click `SEND` button
* input the address of receiver and amount
* click `CREATE TRANSACTION` button
* input wrong password & click `SIGN & SEND TRANSACTION`
* we will see `password is wrong`
* input password again, click `SIGN & SEND TRANSACTION` will be no tips and the amount of sending will be zero

![image](https://user-images.githubusercontent.com/40413672/41633752-ddcb4e82-7472-11e8-92b7-8d06989fc473.png)
![image](https://user-images.githubusercontent.com/40413672/41633758-e9d39b62-7472-11e8-9e93-f8c30adf0c61.png)
![image](https://user-images.githubusercontent.com/40413672/41633781-0c93305e-7473-11e8-9de2-2c1f11eeae8b.png)

**Comment by BelfordZ** [comment]
Thank you for the very detailed issue

**Comment by shanejonas** [comment]
this was fixed when fixing token sending in https://github.com/ETCDEVTeam/emerald-wallet/pull/638. will be out in the next release
