### ISSUE TITLE
Which branch is the latest stable version of the wallet?

### ISSUE THREAD

**Issue by softgg** [ETCDEVTeam/emerald-wallet#644]
If I want to use emerald-wallet for dapp development，which branch do you recommend?

**Comment by splix** [comment]
try `master`

**Comment by softgg** [comment]
when i send my token
![image](https://user-images.githubusercontent.com/14340821/41703517-2a61232c-7566-11e8-80ad-e31cc97c5fac.png)
it always show me 0ETC
![image](https://user-images.githubusercontent.com/14340821/41703460-f44401ec-7565-11e8-9306-423781699e59.png)

where was I wrong?

**Comment by BelfordZ** [comment]
@softgg We are working on fix for this. Currently its showing the ETC amount that was included in the token tx, which is almost always going to be 0.
#651 fixes this. Should be good to go shortly.
