### ISSUE TITLE
delete wallet, how ?

### ISSUE THREAD

**Issue by mishax1** [ETCDEVTeam/emerald-wallet#711]
What do I need to delete so I'll get a new wallet when reinstalling ?

**Comment by BelfordZ** [comment]
What platform are you on? Osx? Windows?

**Comment by mishax1** [comment]
win10

**Comment by mishax1** [comment]
?

**Comment by shanejonas** [comment]
hi @mishax1, the wallet keys are not stored with the executable app, you should be able to delete the old wallet and install a new one and the same accounts should still show up after you upgrade.

**Comment by mishax1** [comment]
So.... how do I delete these accounts from the app ?
