### ISSUE TITLE
Stuck at block 1,495 (0%)

### ISSUE THREAD

**Issue by Aphiso** [ETCDEVTeam/emerald-wallet#714]
For some reason when downloading the blockchain using Emerald, I get stuck with 1,450 blocks remaining. I've had Emerald running for a couple days now so it's definitely stuck and this has happened more than once. Anyone else have this problem or know how to fix it?

I skimmed through the GH issues tracker and didn't see this anywhere else.
![screenshot from 2018-07-10 12-30-45](https://user-images.githubusercontent.com/13264659/42533444-7a0c2a50-844f-11e8-838a-60be9ccfd5fd.png)

I would ouput my logs, but I don't see any log files in my /home/.ethereum-classic folder.

**Comment by splix** [comment]
It takes several days to synchronize blockchain, but it if it doesn't move for last 1450 blocks it seems to be an issue with Geth. We made few fixed to Geth recently that could fix such issues, so I suggest to download latest release https://github.com/ethereumproject/go-ethereum/releases/tag/v5.4.3 manually and run it from command line (with Emerald Wallet shot down at that moment). It will use same directory for blockchain, so you don't need any extra configuration, but you may want to add `--fast` option to make sure it wouldn't start full sync from the beginning.

**Comment by BelfordZ** [comment]
any update on this @Aphiso ?

Note that if you are running geth on your computer, the wallet will connect to it. Make sure you are not running any other geth/parity on port 8545 and then start the wallet.

**Comment by Aphiso** [comment]
@BelfordZ downloading the chain via command line seems to have solved my problem. Sorry been busy and forgot about this.
