### ISSUE TITLE
How to allow rpc access,port 8545 from local network

### ISSUE THREAD

**Issue by AlPato** [ETCDEVTeam/emerald-wallet#716]
Newbie question.After I successfully setup Emerald wallet in full mode,I found it accepts connections from localhost only.How would I allow access from other hosts on a same network ? I know I should run geth with --rpcaddr "0.0.0.0" but how would I do it with Emerald ?

Thank you.

**Comment by splix** [comment]
You can run Geth separately with any option, before Emerald Wallet so it will connect to it automatically

**Comment by AlPato** [comment]
Igor,thank you,I believe I am doing some progress here.Can you please confirm if the following is correct for solo mining

1. geth.exe --nat "any" --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --etherbase "<my wallet address>" console

2. EthDcrMiner64.exe -epool http://<Geth IP>:8545 -ewal <my wallet address> -epsw <my password> -allcoins 1

When I run Claymore I can't see any errors however no jobs are coming in.
Sorry if question is stupid,this is my first time trying mining solo.

Thanks.

**Comment by splix** [comment]
Can't answer that question about mining unfortunately, try to ask at https://forum.ethereumclassic.org/c/mining

**Comment by AlPato** [comment]
I will,thanks.
