### ISSUE TITLE
Payment from Miningpoolhub not showing

### ISSUE THREAD

**Issue by Deeferdawg** [ETCDEVTeam/emerald-wallet#739]
My payments from MiningPoolHub are not being received into m ETC wallet. Addresses are correct so I'm not sure what is going on.

**Comment by sinand99** [comment]
Same here. ETC payments are stuck. Gastracker cannot find the transaction.

**Comment by splix** [comment]
@sinand99 does this transaction exists? can you find it other way, like through RPC API on a full node?

**Comment by sinand99** [comment]
How is this possible? Their log shows the transaction time as 2018-08-08 22:30:35 (UTC) which is 6 hours ago. Can the transaction take that long?? Is there a possibility that transaction can be lost in the network? Or they scam their users now?

**Comment by splix** [comment]
You need to contact your mining pool to resolve the issue

**Comment by Deeferdawg** [comment]
I also got paid from Ethermine and is not showing up in my Emerald Wallet. Payment was at 4:52am this morning. Isn't it weird that two pools have paid out but not showing up in my wallet?

**Comment by splix** [comment]
@Deeferdawg do you see that transaction on a blockexplorer or a full node?

**Comment by Deeferdawg** [comment]
http://gastracker.io/tx/0x56f006a6b9af51d04a2b18e0fcca6993dd0dec95f32990467a77dd77c9ea753e

**Comment by splix** [comment]
also, what do you mean by "_not showing_"? Your balance is not updated, or you don't see transaction in transactions list at the bottom?

**Comment by Deeferdawg** [comment]
I don't see not one transaction in my wallet. Whether it be my balance or IN transactions. As far as I know my wallet is current as it has been open for quite a while

**Comment by splix** [comment]
So the balance is correct?

For IN transactions, it works only if you use a full local node. If you use a remote node, like Gastracker, is will show balance and OUT transactions made _only_ from from the wallet itself.

**Comment by Deeferdawg** [comment]
the balance indicates 0.00

**Comment by Deeferdawg** [comment]
Want me to take a screenshot?

**Comment by splix** [comment]
Do you use full node or a remote node?

**Comment by Deeferdawg** [comment]
Not sure . I just have the wallet on my laptop

**Comment by splix** [comment]
ok, I guess screenshot could help

**Comment by Deeferdawg** [comment]
![15338254385686535857932456075196](https://user-images.githubusercontent.com/35615531/43906028-84de6c3c-9baf-11e8-9f76-94ea0ca25397.jpg)

**Comment by splix** [comment]
You're using a full node, which is good. But the node is still synchronizing, currently at block 1,675,163. Transaction you're looking for is happened at the block 6,337,088 and you need to wait till node will be synchronized to that block, that can take awhile, maybe a week or even more, depending on your hardware.
You can easily switch to a remote node (Mainnet selector), to check if balance is correct.
