### ISSUE TITLE
Does not show "IN" transactions, only "OUT"

### ISSUE THREAD

**Issue by DonaldMcIntyre** [ETCDEVTeam/emerald-wallet#748]
Does not show "IN" transactions, only "OUT", but balances are correct.

**Comment by BelfordZ** [comment]
which build are you using? V1.0 from releases page?

**Comment by BelfordZ** [comment]
Also, if you are using gastracker, you wont get TX history. Try running full node.

**Comment by DonaldMcIntyre** [comment]
Yes using V1.0

Gastracker is the default. When I try to change to "Mainnet Fullnode" it gives me two maessages:

1. "ERROR: An unexpected error has occured. Please restart & update emerald wallet. The error was: Failed to fetch"

2. "You are connected to not synced node, your balances can show wrong value.
About 5910884 blocks left."

Should I change to another of the nodes?

**Comment by DonaldMcIntyre** [comment]
When I choose "Mainnet Fullnode" does that mean it turns my computer into a full node or that it connects remotely to another node?

**Comment by BelfordZ** [comment]
`Mainnet Fullnode` will boot geth, making your computer run a full node. This will require fully syncing the chain, and will take some time. 

If/when gastracker, or other explorers add the RPC commands for getAddressTransactions, then you will be able to see history of tx's sent outside of the wallet.

**Comment by BelfordZ** [comment]
as a side note -- we have discussed revisiting the node options, possibly adding a custom endpoint option which would allow you to specify a remote node address.
