### ISSUE TITLE
Deposit#Shapeshift button/link yields shapeshift 404

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-wallet#822]
![screenshot_20181024_191533](https://user-images.githubusercontent.com/10228550/47468556-86801100-d7c1-11e8-94f2-21f67b88e8b1.png)

![screenshot_20181024_191458](https://user-images.githubusercontent.com/10228550/47468555-86801100-d7c1-11e8-845b-16bd065144e0.png)

> http://builds.etcdevteam.com/emerald-wallet/v1.0.x/EmeraldWallet-linux-x64-v1.0.0+76-a757d01.tar.gz

```
$ uname -a
Linux ubp52 4.17.4-041704-generic #201807031235 SMP Tue Jul 3 12:37:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shanejonas** [comment]
Shapeshift now requires a "Shapeshift Membership".

https://info.shapeshift.io/blog/2018/09/04/introducing-shapeshift-membership/

I've also looked at https://changenow.io which also requires an API key/membership

just going to do some more research on solutions for us here that make sense.

Maybe we take this feature out for the interim?

**Comment by splix** [comment]
Ah, yeah, it seems all of them require KYC now, so we should remove such feature for now

**Comment by paulmadore** [comment]
Possibility of getting morphtoken to add ETC. They don't require membership.
