### ISSUE TITLE
"Light node" is really "Remote node"

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-wallet#823]
![screenshot_20181024_192131](https://user-images.githubusercontent.com/10228550/47468649-10c87500-d7c2-11e8-825f-3d512ea4d469.png)

Has this been discussed before and I just missed that conversation? 

MO is these nodes are better named "Local/Remote" nodes since
- that's how they relate to our computer
- _light_ is a "reserved word," and means something specific in the context of Ethereum nodes (eg. heavy tx pruning and aggressively checkpointed sync and protocol)
- while using geth _locally_, EM could still choose to use "full" or "fast" sync, so _Full node_ in this context is also confounding

**Comment by BelfordZ** [comment]
fixed in coming release
