### ISSUE TITLE
Request: Coinbase integration

### ISSUE THREAD

**Issue by paulmadore** [ETCDEVTeam/emerald-wallet#852]
Coinbase has just announced support of ETC. Hopefully you can integrate it?

**Comment by splix** [comment]
Hi Paul! Can you please elaborate a little bit more how do you see such integration?

**Comment by paulmadore** [comment]
Well hopefully it'd be just like the Eth wallet. You click and enter
details, maybe account is required, and you can buy Etc from coinbase and
it comes to your Emerald wallet a few minutes later.

**Comment by BelfordZ** [comment]
I don't think coinbase wallets allow you to access private keys, meaning you don't really own the crypto you store in coinbase.

If they allowed exporting accounts, then we could work this out. AFAIK, they do not.

**Comment by splix** [comment]
Does Coinbase provide any API for acquisition?
