### ISSUE TITLE
No update to version 1.1.1.

### ISSUE THREAD

**Issue by superiammac** [ETCDEVTeam/emerald-wallet#858]
After opening the dmg file and installing the wallet, the version is still 1.1.0. And he writes that a new version 1.1.1 is available. I download, install and again the same thing - version 1.1.0 is installed.

**Comment by shanejonas** [comment]
Hi, just the version number in the window isn't update. will get a fix in this week for this! Thanks for reporting

**Comment by shanejonas** [comment]
rel #857

**Comment by superiammac** [comment]
Thank. The wallet is cool! We are waiting for updates!

**Comment by shanejonas** [comment]
fix is out. it is on the relases page for `v1.1.1`, thanks again for reporting the issue.
