### ISSUE TITLE
1.3.0-1.3.1-1.3.2

### ISSUE THREAD

**Issue by nn47nn** [ETCDEVTeam/emerald-wallet#947]
Seriously?  Note versoin 1.3.2
Notification about upgrade to 1.3.1
Invalid Sender error on Morden testnet
Wrong version on About screen

compile name EmeraldWallet-win-v1.3.1-9e31997  absolutely the same as in the version 1.3.1 and did not fix anything

**Comment by gagarin55** [comment]
Seriously.

**Comment by nn47nn** [comment]
Лохи ха ха
